" Modeline {

" vim: foldmarker={,} foldlevel=0 foldmethod=marker spell
" Author (more or less) Sever Banesiu <banesiu.sever@gmail.com>

" }

" Loading {

set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
" call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
call vundle#begin('~/.vim/vundleplugins/')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'flazz/vim-colorschemes'
Plugin 'fisadev/vim-isort'
Plugin 'kien/ctrlp.vim'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'gerw/vim-HiLinkTrace'
Plugin 'severb/monoacc'
Plugin 'fatih/vim-go'
Plugin 'Tagbar'
Plugin 'Syntastic'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required


" }

" Bindings {

" I'm using Dvorak and , is a very handy mapleader.
let mapleader = ","

" Comment and uncomment lines of code with this search and replace expression.
" This uses a positive lookahead. How cool is that!?
noremap <leader># :s/^\([\t\ ]*[^\ \t#]\+\)\&/#\ /<cr>
" And here we replace by reusing a group.
noremap <leader>3 :s/^\([\t\ ]*\)#\ \?/\1/<cr>

" Automatically use Python like regex when searching.
nnoremap / /\v
vnoremap / /\v

" Use ,<space> to clear search highlight.
nnoremap <leader><space> :noh<cr>

" Use ,W to remove tailing spaces.
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<cr>

noremap  <F1> <nop>
inoremap <F1> <nop>


" Go shortcuts
au FileType go nmap <leader>gr <Plug>(go-run)
au FileType go nmap <leader>gb <Plug>(go-build)
au FileType go nmap <leader>gt <Plug>(go-test)
au FileType go nmap <leader>gc <Plug>(go-coverage)
" gd is enabled by default, go to definition in the current buffer
au FileType go nmap <Leader>gv <Plug>(go-def-vertical)
au FileType go nmap <Leader>g? <Plug>(go-doc-vertical)

au FileType go nmap <Leader>gi <Plug>(go-implements)
au FileType go nmap <Leader>g/ <Plug>(go-rename)

" }

" Basic {

" Add support for 256 color terminal
set t_Co=256
set nocompatible
set backup
set noswapfile
set incsearch
set ignorecase
set nowrap
set foldenable
set foldmethod=indent
set helplang=En
set history=1024
set undolevels=1024 " use all the undos ever.
set background=dark
set hlsearch " Don't keep the search results highlighted. I hate that.
set title
set shiftwidth=4
set expandtab
set tabstop=8
set encoding=utf-8
set modelines=0
set autoindent
set showmode
set showcmd
set cursorline
set ttyfast
set number
set cpoptions+=J " Sentence followed by two spaces.
set lazyredraw
set splitbelow
set splitright
set notimeout
set nottimeout
set autoread
set dictionary=/usr/share/dict/words
set backupdir=~/.vim/tmp/backup/ " backups
set directory=~/.vim/tmp/swap/   " swap files
syntax on
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
compiler pyunit
colors monoacc
"hi Normal ctermbg=NONE
"hi NonText ctermbg=NONE
"hi SpecialKey ctermbg=NONE
"hi ColorColumn ctermbg=0
set colorcolumn=80

" }

" Advanced {

" Resize splits when the window is resized
au VimResized * exe "normal! \<c-w>="
set hidden " Allow buffers to be changed even if they contain changes.
set noexrc " Don't try to load some configuration files.
set backspace=indent,eol,start " This is supposed to make backspace more flexible.
set keymodel= " I don't want to select using Shift + End or the like.
set showmatch " Show matching parenthesis
set smartcase " Ignore case if search pattern is all lowercase,
set gdefault " By default use a global replace instead of line replace
set ruler " Shows the line and col number. Can be customized.
set selection=exclusive " When selecting from right to left, the last char isn't included.
set selectmode= " Why do I need a Select mode?
set wildignore=*.pyc,*~,*.pyw,.hg,.svn,.git,*.swp,*.bak " What to ignore when search a filename.
set wildmode=list:full " How to display the file list when searching.
" No damn visual, audio or error bell.
set noerrorbells
set novisualbell
" Kill the bells with fire.
autocmd GUIEnter * set vb t_vb=
autocmd VimEnter * set vb t_vb=
set vb t_vb=".
set clipboard+=unnamed " Share clipboard with Windows. Aww...
set iskeyword+=_ " Underscore is part of a word in my world.
set laststatus=2 " Always display status line.
set linespace=0 " No empty spaces between the rows.
set list " Show whitespaces so I can remove them, doo'h!
set listchars=tab:·\ ,eol:¬,trail:»
set matchtime=3 " Blinks the matching bracket.
set statusline=%F%m%r%h%w[%L][%{&ff}]%y[%p%%][%04l,%04v] " Don't ask!
set shell=bash

" }

" GUI {

" Wont work if vim is started from console and then :gui
if has("gui_running")
	set guifont=Fantasque\ Sans\ Mono\ 14
	" There are a bunch of options here, I don't want most of them.
	" This hides everything uses simple dialogues as opposed to pop-ups.
	set guioptions=
	highlight SpellBad term=underline gui=undercurl guisp=Orange
endif

" }

" Autocmds {

autocmd FileType python setlocal completeopt-=preview
autocmd BufEnter * :syntax sync fromstart " Slower but better syntax highlight
au BufNewFile *.go,*.py,*.pyw,*.c,*.h set fileformat=unix

" }

" Extension configurations {

let g:syntastic_auto_loc_list = 2 " Auto close error window but don't open.
let g:syntastic_check_on_open=1
let g:syntastic_enable_signs=1 " Put errors on left side
let g:syntastic_python_checkers=['python', 'pylint']
let g:syntastic_go_checkers=['go', 'gofmt', 'golint', 'govet', 'errcheck']

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

let g:ctrlp_cmd = 'CtrlPMixed'
let python_highlight_all = 1

let g:airline_theme = 'bubblegum'

let g:go_highlight_functions = 1
" let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

let g:go_fmt_command = "goimports"

" }
